add test report to github workflow

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -6,6 +6,8 @@ on:
   pull_request:
     branches:
       - main
+permissions:
+  checks: write
 jobs:
   build:
     name: Build, Test, and Analyze
@@ -33,6 +35,14 @@ jobs:
           restore-keys: ${{ runner.os }}-gradle
       - name: Build
         run: ./gradlew build
+      - name: Debug token
+        run: echo "Token is ${{ secrets.JUNIT_REPORT_GITHUB_TOKEN }}"
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          token: ${{ secrets.JUNIT_REPORT_GITHUB_TOKEN }}
       - name: Analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
